/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as TripIdRouteImport } from './routes/trip.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/drive': typeof DriveRoute
  '/plan': typeof PlanRoute
  '/policy': typeof PolicyRoute
  '/readiness': typeof ReadinessRoute
  '/trip/$id': typeof TripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/drive': typeof DriveRoute
  '/plan': typeof PlanRoute
  '/policy': typeof PolicyRoute
  '/readiness': typeof ReadinessRoute
  '/trip/$id': typeof TripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/drive': typeof DriveRoute
  '/plan': typeof PlanRoute
  '/policy': typeof PolicyRoute
  '/readiness': typeof ReadinessRoute
  '/trip/$id': typeof TripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/agent' | '/drive' | '/plan' | '/policy' | '/readiness' | '/trip/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/agent' | '/drive' | '/plan' | '/policy' | '/readiness' | '/trip/$id'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/drive'
    | '/plan'
    | '/policy'
    | '/readiness'
    | '/trip/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  DriveRoute: typeof DriveRoute
  PlanRoute: typeof PlanRoute
  PolicyRoute: typeof PolicyRoute
  ReadinessRoute: typeof ReadinessRoute
  TripIdRoute: typeof TripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  DriveRoute: DriveRoute,
  PlanRoute: PlanRoute,
  PolicyRoute: PolicyRoute,
  ReadinessRoute: ReadinessRoute,
  TripIdRoute: TripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
